config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :phone_number, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
  validates_associated :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating,  numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :set_restaurant, only: %i[show edit update destroy chef]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def review
    @review = Review.new
    @review = @restaurant.review
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone_number, :address, :category)
  end

  # def set_restaurant

  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end
  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div>
  <h1>List of restaurants</h2>
  <br>
  <div>
    <ul>
      <% @restaurants.each do |restaurant| %>
         <li>
           <%= link_to restaurant.name, restaurant_path(restaurant) %>
         </li>
      <% end %>
    </ul>
  </div>
  <br>
   <%= link_to "Add restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="m-5">
  <h1>New restaurant</h1>
  <%= simple_form_for [@restaurant] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/review.html.erb
<div>
  <h1><%= @restaurant.name %></h1>
  <br>
  <p><%= @review.content %></p>
  <%= link_to "Back to restaurants", restaurants_show_path(@restaurant) %>
</div>

app/views/restaurants/show.html.erb
<div class="m-5">
  <h1><%= @restaurant.name %></h1>
  <br>
  <h3><strong>Address:</strong> <%= @restaurant.address %></h3>
  <h3><strong>Phone number:</strong> <%= @restaurant.phone_number %></h3>
  <h3><strong>Category:</strong> <%= @restaurant.category %></h3>
  <br>
  <h3><strong>Reviews</strong></h3>
  <%= link_to "Add review", new_restaurant_review_path(@restaurant) %>
  <ul>
   <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.rating %></li>
      <li class="list-group-item"><%= review.content %></li>
      <% end %>
   </ul>
  <%= link_to "Back to restaurants", restaurants_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<div class="m-5">
  <h1>New review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>